cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"

brew "dnsmasq"
brew "docker"
brew "docker-machine"
brew "elixir"
brew "git"
brew "heroku"
brew "hub"
brew "yarn"
brew "zsh"
brew "zsh-completions"
